<a href="https://colab.research.google.com/github/langodayyy/ml/blob/main/ML_week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nama  : Lucky Kurniawan Langoday <br>
Kelas : TI-3D <br>
Absen : 13 <br>
NIM   : 2241720168

In [ ]:
def norm_data(data):
  '''
  melakukan normalisasi data
  Parameters:
    data (list) : data yang akan dinormalisasi
  Returns:
    data (list) : data yang sudah dinormalisasi
  '''

  data_max = max(data)
  data_min = min(data)
  data_len = len(data)

  for i in range(0, data_len):
    data[i] = (data[i] - data_min) / (data_max - data_min)

  return data

#contoh penggunaan
data = [10, 11, 12, 14, 16]
n_data = norm_data(data) #melakukan normalisasi
print(n_data)


[0.0, 0.16666666666666666, 0.3333333333333333, 0.6666666666666666, 1.0]


In [2]:
import numpy as np

from sklearn.preprocessing import MinMaxScaler

np.set_printoptions(precision=6)
np.set_printoptions(suppress=True)

#membentuk data
data = [
    [100, 0.0001],
    [50, 0.05],
    [30, 0.003]
]

#ubah e bentuk numpy n-dimensional array
data = np.asarray(data)
print('Data Asli')
print(data)

#mendefinisikan obyek minmaxscaler
scaler = MinMaxScaler()
#transformasikan data
scaled = scaler.fit_transform(data)
print('Data Setelah Di-Normalisasi')
print(scaled)


Data Asli
[[100.       0.0001]
 [ 50.       0.05  ]
 [ 30.       0.003 ]]
Data Setelah Di-Normalisasi
[[1.       0.      ]
 [0.285714 1.      ]
 [0.       0.058116]]


In [3]:
import numpy as np
from sklearn.preprocessing import StandardScaler

np.set_printoptions(precision=6)
np.set_printoptions(suppress=True)

#membentuk data
data = [
    [100, 0.0001],
    [50, 0.05],
    [30, 0.003]
]

#ubah ke bentuk numpy n-dimensional array
data = np.asarray(data)
print('Data Asli')
print(data)

#mendefinisikan obyek standardscaler
scaler = StandardScaler()
#transformasikan data
scaled = scaler.fit_transform(data)
print('Data standarisasi')
print(scaled)

Data Asli
[[100.       0.0001]
 [ 50.       0.05  ]
 [ 30.       0.003 ]]
Data standarisasi
[[ 1.358732 -0.76956 ]
 [-0.339683  1.412317]
 [-1.019049 -0.642757]]


In [4]:
from sklearn.preprocessing import OrdinalEncoder

#inisialisasi obyek
oe = OrdinalEncoder()

#definisikan data ke dalam bentuk 2d
data=[
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarta'],
    ['Politeknik Negeri Semarang'],
]

#transformasi Ordinal Encoder
transform_oe = oe.fit_transform(data)
print('Data asli')
print(data)
print('Data setelah di transformasi Ordinal Encoder')
print(transform_oe)

Data asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarta'], ['Politeknik Negeri Semarang']]
Data setelah di transformasi Ordinal Encoder
[[2.]
 [0.]
 [1.]
 [3.]]


In [10]:
from sklearn.preprocessing import OneHotEncoder

# inisialisasi obyek one hot encoder
ohe = OneHotEncoder()

#definisikan data ke dalam bentuk 2d
data=[
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarta'],
    ['Politeknik Negeri Semarang'],
]

#transformasi one hot encoder
transform_ohe = ohe.fit_transform(data)

print('Data asli')
print(data)

print('Data transformasi one hot encoding')
print(transform_ohe.toarray())

Data asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarta'], ['Politeknik Negeri Semarang']]
Data transformasi one hot encoding
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


In [11]:
from sklearn.preprocessing import OneHotEncoder

#inisial obyek ordinal encoder
de = OneHotEncoder(drop='first')

#definisikan data ke dalam bentuk 2d
data=[
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarta'],
    ['Politeknik Negeri Semarang'],
]

#transformasi ordinal encoder
transform_de = de.fit_transform(data)

print('Data asli')
print(data)

print('Data transformasi one-Hot Encoding')
print(transform_de.toarray())

Data asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarta'], ['Politeknik Negeri Semarang']]
Data transformasi one-Hot Encoding
[[0. 1. 0.]
 [0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
    'the house had a tiny little mouse',
    'the cat saw the mouse',
    'the mouse ran away from the house',
    'the cat finally ate the mouse',
    'the end of the mouse story'
]

#inisialisasi obyek TFidVectorizer
vect = TfidfVectorizer(stop_words='english')

#pembobotan TF-IDF
resp = vect.fit_transform(corpus)

#cetak hasil
print("Hasil TF-IDF")
print(resp)

#cetak token hasil stopword
print("Token hasil stopword")
print(vect.get_feature_names_out())

Hasil TF-IDF
  (0, 7)	0.2808823162882302
  (0, 6)	0.5894630806320427
  (0, 11)	0.5894630806320427
  (0, 5)	0.47557510189256375
  (1, 9)	0.7297183669435993
  (1, 2)	0.5887321837696324
  (1, 7)	0.3477147117091919
  (2, 1)	0.5894630806320427
  (2, 8)	0.5894630806320427
  (2, 7)	0.2808823162882302
  (2, 5)	0.47557510189256375
  (3, 0)	0.5894630806320427
  (3, 4)	0.5894630806320427
  (3, 2)	0.47557510189256375
  (3, 7)	0.2808823162882302
  (4, 10)	0.6700917930430479
  (4, 3)	0.6700917930430479
  (4, 7)	0.3193023297639811
Token hasil stopword
['ate' 'away' 'cat' 'end' 'finally' 'house' 'little' 'mouse' 'ran' 'saw'
 'story' 'tiny']


In [22]:
with open('corpus.txt', 'r') as f:
    data = f.read()

from sklearn.feature_extraction.text import TfidfVectorizer
#inisialisasi obyek TFidVectorizer
vect = TfidfVectorizer(stop_words='english')

#pembobotan TF-IDF
resp = vect.fit_transform(corpus)

#cetak hasil
print("Hasil TF-IDF")
print(resp)

#cetak token hasil stopword
print("Token hasil stopword")
print(vect.get_feature_names_out())

Hasil TF-IDF
  (0, 7)	0.2808823162882302
  (0, 6)	0.5894630806320427
  (0, 11)	0.5894630806320427
  (0, 5)	0.47557510189256375
  (1, 9)	0.7297183669435993
  (1, 2)	0.5887321837696324
  (1, 7)	0.3477147117091919
  (2, 1)	0.5894630806320427
  (2, 8)	0.5894630806320427
  (2, 7)	0.2808823162882302
  (2, 5)	0.47557510189256375
  (3, 0)	0.5894630806320427
  (3, 4)	0.5894630806320427
  (3, 2)	0.47557510189256375
  (3, 7)	0.2808823162882302
  (4, 10)	0.6700917930430479
  (4, 3)	0.6700917930430479
  (4, 7)	0.3193023297639811
Token hasil stopword
['ate' 'away' 'cat' 'end' 'finally' 'house' 'little' 'mouse' 'ran' 'saw'
 'story' 'tiny']


In [24]:
!jupyter nbconvert --to html /content/ML_week2.ipynb

[NbConvertApp] Converting notebook /content/ML_week2.ipynb to html
[NbConvertApp] Writing 599955 bytes to /content/ML_week2.html
